################################################################################
# pipeline.R — scRNA-seq Preprocessing Pipeline
#
# Orchestrates the full preprocessing workflow by sourcing modular components.
# All logic lives in modules/; this script reads like a pseudocode outline.
#
# Steps:
#   1. CellRanger experiment summary + visualizations
#   2. Ambient RNA removal (DecontX)
#   2b. Pre-filter QC visualizations
#   3. Doublet detection (DoubletFinder + scds) — before QC filtering
#   4. Seurat QC filtering, normalization, and clustering
#   5. Batch effect evaluation (silhouette + UMAP, only if BATCH_COLS defined)
#
# Usage:
#   Rscript pipeline.R config.R
#
# Do NOT edit this file for new projects. Edit config.R and samples.tsv only.
################################################################################

options(stringsAsFactors = FALSE)

# ── Load config ───────────────────────────────────────────────────────────────

args        <- commandArgs(trailingOnly = TRUE)
config_file <- if (length(args) >= 1) args[1] else "config.R"

if (!file.exists(config_file))
  stop("Config file not found: ", config_file,
       "\nUsage: Rscript pipeline.R config.R")

source(config_file)
message("Loaded config from: ", config_file)

# ── Load sample metadata ──────────────────────────────────────────────────────

if (!file.exists(METADATA_FILE))
  stop("Metadata file not found: ", METADATA_FILE,
       "\nSet METADATA_FILE in config.R to the path of your sample sheet.")

sep             <- if (grepl("\\.tsv$", METADATA_FILE, ignore.case = TRUE)) "\t" else ","
SAMPLE_METADATA <- read.table(METADATA_FILE, header = TRUE, sep = sep,
                               stringsAsFactors = FALSE, check.names = FALSE)

required_cols <- c("sample_id", "fastq_sample_name")
missing_cols  <- setdiff(required_cols, colnames(SAMPLE_METADATA))
if (length(missing_cols) > 0)
  stop("Metadata file is missing required columns: ",
       paste(missing_cols, collapse = ", "))

message("Loaded ", nrow(SAMPLE_METADATA), " samples from: ", METADATA_FILE)

# ── Source package checker and load all libraries ─────────────────────────────
# Must happen before sourcing other modules

module_dir <- file.path(dirname(normalizePath(config_file)), "modules")
if (!dir.exists(module_dir))
  module_dir <- "modules"

pkg_check_path <- file.path(module_dir, "check_packages.R")
if (!file.exists(pkg_check_path))
  stop("Module not found: ", pkg_check_path)

source(pkg_check_path)
check_and_install_packages()

# ── Derived config ────────────────────────────────────────────────────────────

# All metadata covariate columns (used for annotation and QC grouping)
METADATA_COVARIATE_COLS <- setdiff(colnames(SAMPLE_METADATA),
                                   c("sample_id", "fastq_sample_name"))

# Validate BATCH_COLS; default gracefully if missing from an older config
if (!exists("BATCH_COLS")) {
  warning("BATCH_COLS not found in config. Defaulting to character(0). ",
          "Add BATCH_COLS to config.R to suppress this warning.")
  BATCH_COLS <- character(0)
}

unknown_batch <- setdiff(BATCH_COLS, colnames(SAMPLE_METADATA))
if (length(unknown_batch) > 0) {
  warning("BATCH_COLS references column(s) not in metadata: ",
          paste(unknown_batch, collapse = ", "), " — skipping.")
  BATCH_COLS <- intersect(BATCH_COLS, colnames(SAMPLE_METADATA))
}

# SCTransform regression: QC metrics + decontX + batch (not biological variables)
SCT_VARS_TO_REGRESS <- unique(c(SCT_EXTRA_VARS, "decontX_contamination", BATCH_COLS))
message("SCTransform will regress out: ", paste(SCT_VARS_TO_REGRESS, collapse = ", "))

# Column used to split and group by sample throughout
SPLIT_BY <- "sample_id"

# Default UMAP settings if missing from older config
if (!exists("UMAP_METHOD")) UMAP_METHOD <- "uwot"
if (!exists("UMAP_METRIC")) UMAP_METRIC <- "cosine"

# ── Source remaining modules ──────────────────────────────────────────────────

for (mod in c("utils.R", "cellranger_summary.R", "decontx.R",
              "qc_visualization.R", "doublet_detection.R", "seurat_qc.R",
              "batch_evaluation.R")) {
  path <- file.path(module_dir, mod)
  if (!file.exists(path))
    stop("Module not found: ", path,
         "\nExpected modules/ directory alongside config.R or in working directory.")
  source(path)
}

message("All modules loaded.\n")

# ── Create output directories ─────────────────────────────────────────────────

dir.create(OUTPUT_DIR, recursive = TRUE, showWarnings = FALSE)
PLOT_DIR <- file.path(OUTPUT_DIR, "plots")
dir.create(PLOT_DIR, recursive = TRUE, showWarnings = FALSE)
message("Output directory : ", OUTPUT_DIR)
message("Plot directory   : ", PLOT_DIR, "\n")

pipeline_start <- proc.time()
message("Pipeline started: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n")

################################################################################
# STEP 1: CellRanger experiment summary
################################################################################

t1_start <- proc.time()
qc_stats <- run_cellranger_summary()
t1_end   <- proc.time()

################################################################################
# STEP 2: Ambient RNA removal — DecontX
################################################################################

t2_start   <- proc.time()
seurat_obj <- run_decontx()
t2_end     <- proc.time()

################################################################################
# STEP 2b: QC visualizations (pre-filter, full dataset)
################################################################################

t2b_start  <- proc.time()
seurat_obj <- run_qc_visualization(seurat_obj)
t2b_end    <- proc.time()

################################################################################
# STEP 3: Doublet detection (before QC filtering)
################################################################################

t3_start        <- proc.time()
seurat_singlets <- run_doublet_detection(seurat_obj)
rm(seurat_obj); gc()
t3_end          <- proc.time()

################################################################################
# STEP 4: Seurat QC filtering, normalization, and clustering
################################################################################

t4_start    <- proc.time()
seurat_filt <- run_seurat_qc(seurat_singlets)
rm(seurat_singlets); gc()
t4_end      <- proc.time()

################################################################################
# STEP 5: Batch effect evaluation (only when BATCH_COLS is defined and non-empty)
################################################################################

t5_start <- proc.time()
if (length(BATCH_COLS) > 0) {
  run_batch_evaluation(seurat_filt)
} else {
  message("No BATCH_COLS defined — skipping batch evaluation.")
}
t5_end <- proc.time()

################################################################################
# Timing summary
################################################################################

fmt_step <- function(start, end) {
  secs <- round((end - start)[["elapsed"]])
  sprintf("%02d:%02d:%02d", secs %/% 3600, (secs %% 3600) %/% 60, secs %% 60)
}

timing_df <- data.frame(
  Step     = c("1: CellRanger summary",
               "2: DecontX",
               "2b: QC visualizations",
               "3: Doublet detection",
               "4: Seurat QC + clustering",
               "5: Batch evaluation"),
  Duration = c(fmt_step(t1_start,  t1_end),
               fmt_step(t2_start,  t2_end),
               fmt_step(t2b_start, t2b_end),
               fmt_step(t3_start,  t3_end),
               fmt_step(t4_start,  t4_end),
               fmt_step(t5_start,  t5_end)),
  stringsAsFactors = FALSE
)

total_secs    <- round((proc.time() - pipeline_start)[["elapsed"]])
total_hms     <- sprintf("%02d:%02d:%02d",
                         total_secs %/% 3600,
                         (total_secs %% 3600) %/% 60,
                         total_secs %% 60)

message("\n════════════════════════════════════════")
message("  Pipeline timing summary (hh:mm:ss)")
message("════════════════════════════════════════")
for (i in seq_len(nrow(timing_df)))
  message(sprintf("  %-28s %s", timing_df$Step[i], timing_df$Duration[i]))
message("────────────────────────────────────────")
message(sprintf("  %-28s %s", "Total", total_hms))
message("════════════════════════════════════════\n")

write.table(timing_df, file = stamp("timing_summary", ext = "txt"),
            sep = "\t", row.names = FALSE, quote = FALSE)

################################################################################
# Session info
################################################################################

sink(stamp("session_info", ext = "txt"))
sessionInfo()
sink()

message("Pipeline complete: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
