################################################################################
# prepare_cellranger.R — CellRanger Job Preparation
#
# Validates FASTQ file naming and generates a shell script for submission
# to an HPC cluster. Does NOT run CellRanger directly.
#
# Steps:
#   1. Validate FASTQ file naming (flag or rename to CellRanger convention)
#   2. Generate a CellRanger shell script to submit on HPC
#
# Usage:
#   Rscript prepare_cellranger.R config.R           # validate + generate script
#   Rscript prepare_cellranger.R config.R --rename  # validate + rename + generate script
#
# Expected FASTQ naming convention (CellRanger requirement):
#   [SampleName]_S[Index]_L00[Lane]_[ReadType]_001.fastq.gz
#   e.g. MySample_S1_L001_R1_001.fastq.gz
#
# After CellRanger finishes, run pipeline.R which extracts the QC summary
# as its first step before proceeding with preprocessing.
#
# Do NOT edit this file. Edit config.R and samples.tsv only.
################################################################################

options(stringsAsFactors = FALSE)

# ── Parse arguments ───────────────────────────────────────────────────────────

args        <- commandArgs(trailingOnly = TRUE)
config_file <- if (length(args) >= 1 && !startsWith(args[1], "--")) args[1] else "config.R"
do_rename   <- "--rename" %in% args

if (!file.exists(config_file)) {
  stop("Config file not found: ", config_file,
       "\nUsage: Rscript prepare_cellranger.R config.R [--rename]")
}
source(config_file)
message("Loaded config from: ", config_file)

# ── Load metadata ─────────────────────────────────────────────────────────────

if (!file.exists(METADATA_FILE)) {
  stop("Metadata file not found: ", METADATA_FILE)
}

sep             <- if (grepl("\\.tsv$", METADATA_FILE, ignore.case = TRUE)) "\t" else ","
SAMPLE_METADATA <- read.table(METADATA_FILE, header = TRUE, sep = sep,
                               stringsAsFactors = FALSE, check.names = FALSE)

required_cols <- c("sample_id", "fastq_sample_name")
missing_cols  <- setdiff(required_cols, colnames(SAMPLE_METADATA))
if (length(missing_cols) > 0) {
  stop("Metadata file is missing required columns: ",
       paste(missing_cols, collapse = ", "))
}

message("Loaded ", nrow(SAMPLE_METADATA), " samples from: ", METADATA_FILE)

# ── Helpers ───────────────────────────────────────────────────────────────────

cellranger_paths <- function(sid) {
  base <- file.path(CELLRANGER_OUTDIR, sid, "outs")
  list(
    filtered = file.path(base, "filtered_feature_bc_matrix"),
    raw      = file.path(base, "raw_feature_bc_matrix"),
    metrics  = file.path(base, "metrics_summary.csv")
  )
}

stamp_cr <- function(..., ext) {
  fname <- paste(c(as.character(Sys.Date()), PROJECT_NAME, ...), collapse = "_")
  file.path(OUTPUT_DIR, paste0(fname, ".", ext))
}

# CellRanger required pattern:
#   [SampleName]_S[digit(s)]_L00[digit]_[ReadType]_001.fastq.gz
# Read types: R1, R2, R3, I1, I2
CELLRANGER_FASTQ_PATTERN <- "^(.+)_(S[0-9]+)_(L[0-9]{3})_(R[123]|I[12])_001\\.fastq(\\.gz)?$"

################################################################################
# STEP 1: Validate (and optionally rename) FASTQ files
################################################################################

message("\n── FASTQ validation ──────────────────────────────────────────────────────────")

# Scan the FASTQ directory once, then filter per sample — avoids rescanning
# the filesystem on every loop iteration
all_fastqs    <- list.files(FASTQ_DIR, recursive = TRUE,
                             pattern = "\\.fastq(\\.gz)?$", full.names = TRUE)
all_basenames <- basename(all_fastqs)

#' Parse one FASTQ filename and return a suggested CellRanger-compliant name.
#' Returns NA_character_ if parsing fails.
suggest_fastq_name <- function(fname, sample_name) {
  base <- sub("\\.fastq\\.gz$|\\.fastq$|\\.gz$", "", fname)

  lane_match <- regmatches(base, regexpr("(?i)l(?:ane)?[_-]?0*([1-9][0-9]*)", base, perl = TRUE))
  lane_num   <- if (length(lane_match) > 0)
                  sprintf("L%03d", as.integer(sub("(?i)l(?:ane)?[_-]?0*", "", lane_match, perl = TRUE)))
                else "L001"

  read_match <- regmatches(base, regexpr("(?i)(R[123]|I[12])", base, perl = TRUE))
  read_type  <- if (length(read_match) > 0) toupper(read_match) else "R1"

  idx_match <- regmatches(base, regexpr("_S([0-9]+)_", base, perl = TRUE))
  s_index   <- if (length(idx_match) > 0)
                 sub("^_|_$", "", idx_match)
               else "S1"

  paste0(sample_name, "_", s_index, "_", lane_num, "_", read_type, "_001.fastq.gz")
}

#' Validate all FASTQ files for one sample; return a data.frame of issues
#' (zero rows if everything is valid).
validate_sample_fastqs <- function(sample_id, sample_name, fastq_paths) {

  fnames <- basename(fastq_paths)
  valid  <- grepl(CELLRANGER_FASTQ_PATTERN, fnames, perl = TRUE)

  issues <- list()

  # ── Files that match the pattern: check sample name portion ─────────────────
  for (fq in fastq_paths[valid]) {
    fname         <- basename(fq)
    detected_name <- sub(CELLRANGER_FASTQ_PATTERN, "\\1", fname, perl = TRUE)
    if (detected_name != sample_name) {
      issues[[fname]] <- data.frame(
        sample_id = sample_id,
        file      = fq,
        issue     = paste0("Sample name mismatch: file has '", detected_name,
                           "', expected '", sample_name, "'"),
        suggested = file.path(dirname(fq),
                              sub(paste0("^", detected_name), sample_name,
                                  fname, fixed = TRUE)),
        stringsAsFactors = FALSE
      )
    }
  }

  # ── Files that don't match the pattern: suggest a corrected name ─────────────
  for (fq in fastq_paths[!valid]) {
    fname     <- basename(fq)
    suggested <- tryCatch(suggest_fastq_name(fname, sample_name),
                          error = function(e) NA_character_)
    issues[[fname]] <- data.frame(
      sample_id = sample_id,
      file      = fq,
      issue     = "Does not match CellRanger naming convention",
      suggested = if (!is.na(suggested)) file.path(dirname(fq), suggested)
                  else NA_character_,
      stringsAsFactors = FALSE
    )
  }

  if (length(issues) > 0) do.call(rbind, issues) else data.frame()
}

# ── Run validation across all samples ─────────────────────────────────────────

all_issues <- lapply(seq_len(nrow(SAMPLE_METADATA)), function(i) {
  sample_id   <- SAMPLE_METADATA$sample_id[i]
  sample_name <- SAMPLE_METADATA$fastq_sample_name[i]

  # Filter the already-scanned file list to this sample's files
  sample_fastqs <- all_fastqs[grepl(sample_name, all_basenames, fixed = TRUE)]

  if (length(sample_fastqs) == 0) {
    return(data.frame(
      sample_id = sample_id, file = NA_character_,
      issue     = "No FASTQ files found", suggested = NA_character_,
      stringsAsFactors = FALSE
    ))
  }

  validate_sample_fastqs(sample_id, sample_name, sample_fastqs)
})

# Drop empty data frames (samples with no issues) and row-bind the rest
all_issues <- do.call(rbind, Filter(function(x) nrow(x) > 0, all_issues))
if (is.null(all_issues)) all_issues <- data.frame()

# ── Report ────────────────────────────────────────────────────────────────────

if (nrow(all_issues) == 0) {

  message("All FASTQ files match the CellRanger naming convention. Ready to proceed.")

} else {

  rownames(all_issues) <- NULL

  report_file <- stamp_cr("FASTQ_naming_issues", ext = "txt")
  write.table(all_issues, file = report_file, sep = "\t",
              row.names = FALSE, quote = FALSE)
  message("Found ", nrow(all_issues), " FASTQ naming issue(s). Report saved to: ", report_file)
  message("")

  for (j in seq_len(nrow(all_issues))) {
    r <- all_issues[j, ]
    if (is.na(r$file)) {
      message("  [", r$sample_id, "] ", r$issue)
    } else {
      message("  [", r$sample_id, "] ", basename(r$file))
      message("           Issue:     ", r$issue)
      if (!is.na(r$suggested)) {
        message("           Suggested: ", basename(r$suggested))
      }
    }
    message("")
  }

  # ── Optional rename ─────────────────────────────────────────────────────────

  if (do_rename) {

    renameable <- all_issues[!is.na(all_issues$file) & !is.na(all_issues$suggested), ]
    no_suggest <- all_issues[!is.na(all_issues$file) &  is.na(all_issues$suggested), ]
    not_found  <- all_issues[ is.na(all_issues$file), ]

    if (nrow(not_found) > 0) {
      message("Cannot rename — files not found for: ",
              paste(not_found$sample_id, collapse = ", "))
    }
    if (nrow(no_suggest) > 0) {
      message("Cannot rename — no valid suggestion for:")
      for (j in seq_len(nrow(no_suggest))) {
        message("  ", basename(no_suggest$file[j]))
      }
    }

    if (nrow(renameable) > 0) {
      message("Renaming ", nrow(renameable), " file(s)...")
      rename_log <- data.frame(original = character(), renamed = character(),
                               status   = character(), stringsAsFactors = FALSE)
      for (j in seq_len(nrow(renameable))) {
        old <- renameable$file[j]
        new <- renameable$suggested[j]
        if (file.exists(new)) {
          status <- "SKIPPED (target already exists)"
        } else {
          ok     <- file.rename(old, new)
          status <- if (ok) "OK" else "FAILED"
        }
        message("  ", basename(old), " → ", basename(new), "  [", status, "]")
        rename_log <- rbind(rename_log,
                            data.frame(original = old, renamed = new,
                                       status = status, stringsAsFactors = FALSE))
      }
      log_file <- stamp_cr("FASTQ_rename_log", ext = "txt")
      write.table(rename_log, file = log_file, sep = "\t",
                  row.names = FALSE, quote = FALSE)
      message("Rename log saved to: ", log_file)
    }

  } else {
    message("Re-run with --rename to automatically rename files to the suggested names.")
    message("Review the report before renaming: ", report_file)
  }

  # If any files are still missing or unresolvable, stop before generating script
  unresolvable <- all_issues[is.na(all_issues$file) | is.na(all_issues$suggested), ]
  if (!do_rename && nrow(all_issues) > 0) {
    message("\nWarning: FASTQ issues detected. CellRanger shell script will still be",
            " generated,\nbut jobs may fail until naming is corrected.")
  } else if (do_rename && nrow(unresolvable) > 0) {
    message("\nWarning: ", nrow(unresolvable), " issue(s) could not be auto-resolved.",
            " Review the report and fix manually before running CellRanger.")
  }
}

################################################################################
# STEP 2: Generate CellRanger shell script
################################################################################

message("\n── Generating CellRanger shell script ────────────────────────────────────────")

cellranger_cmds <- mapply(function(sid, fastq_name) {
  sprintf(
    paste0(
      "%s count \\\n",
      "  --id %s \\\n",
      "  --transcriptome %s \\\n",
      "  --fastqs %s \\\n",
      "  --sample %s \\\n",
      "  --localmem %d \\\n",
      "  --localcores %d"
    ),
    CELLRANGER_PATH, sid, TRANSCRIPTOME_PATH,
    FASTQ_DIR, fastq_name, LOCALMEM, LOCALCORES
  )
}, SAMPLE_METADATA$sample_id, SAMPLE_METADATA$fastq_sample_name)

sh_file <- file.path(OUTPUT_DIR,
                     paste0(Sys.Date(), "_", PROJECT_NAME, "_run_cellranger.sh"))
writeLines(c("#!/bin/bash", "", cellranger_cmds), sh_file)
message("Shell script written to: ", sh_file)
message("Submit on your HPC, then run pipeline.R once all jobs complete.")


